### ISSUE TITLE
Not Logging In

### ISSUE THREAD

**Issue by andycoates** [auth0/auth0-joomla#1]
I've done what it says and I can see the login form on my site (Joomla 3.4.1), but when I try and login, it goes through the motions (I can see it calling auth0 and then redirecting back to my site) but it doesn't seem to recognise that the user is logged in, and it still shows the auth0 login form/button.

I've also enabled user registration but the login form doesn't show any reference to signup, just logging in.

Feels like something is missing but I'm not sure where to look.

**Comment by glena** [comment]
Hi @andycoates sorry for the delay.

Where you able to make it work or it is still not working?

Are you using the latest version from this repository?

Did you check this guide to install (https://auth0.com/docs/cms/joomla/installation) and this now to set it up (https://auth0.com/docs/cms/joomla/configuration)?

**Comment by andycoates** [comment]
I've made some progress today.  It seems as if logging in with a Social provider works (Joomla recognises the user is logged in and creates a user), but logging in with an Auth0 DB created account it still prompts for login and doesn't create the user.

**Comment by glena** [comment]
mmm, does the user have verified the email?

can you check this on the auth0 dashboard? go to users, find the one you are using and check near the email what it says.

if it is not, verify it and try again, maybe just it is not showing the error message.

**Comment by andycoates** [comment]
yes the user has email verified, and I've successfully logged into other applications we have that use Auth0 (e.g. Discourse, apache mod_auth_openidc).   The Lock login prompt also recognises that I have somewhat logged in because it has the "Last time you signed in using..." prompt - it's as if its just the Joomla side of things not being triggered.

**Comment by glena** [comment]
ok, let me run some tests and will get back to you.
Also, which is your auth0 subdomain?

**Comment by andycoates** [comment]
I feel like a dumbass, I think I know what the issue is.  I'd been playing with rules and deleting accounts, and it seems at one point the account was created in Joomla (was surprised to find it there when I went to clean out users just now).  So I did a bit of testing and I think I spot the problem - it seems the first time it creates a user, but then if you delete that user in Auth0, and re-create it (same email etc), it then won't log in to Joomla (but Auth0 thinks you have).  I'm guessing this is something to do with how Joomla links the accounts?  I don't think this would be a real-world issue for us, just an edge case, but does that sound plausible?

**Comment by glena** [comment]
Makes sense and yes it is an edge case.
I think it is not linking existing accounts with auth0's right now.
We want at some point add this linking users feature with existing accounts (we already do that on the wordpress plugin), it is in our backlog.

Glad to know you figured out and have it working now :)
