### ISSUE TITLE
Redirect URL after login

### ISSUE THREAD

**Issue by leveltensolutions** [auth0/auth0-joomla#3]
After login in joomla website plugin does not allow me to configure redirect to specific page by user group. 

Also it does not allow user to signup in different user group. Can you please help me to fix this issue or release new version. 

Please check support ticket ID #4576 for details

Thank you
Maqsood

**Comment by Beejer** [comment]
Have same issue with redirect.  Would prefer a stay-on-same-page option, with a javascript event triggered for updating user name on page.

**Comment by glena** [comment]
It is on the backlog but not a priority right now.
Anyway, if you are willing to contribute, I can guide you on one posible solution for this behaviour.

**Comment by glena** [comment]
I answered the support ticket.
