### ISSUE TITLE
User not logged into Joomla

### ISSUE THREAD

**Issue by Beejer** [auth0/auth0-joomla#4]
Hello,

User is authenticated in Auth0 and shows up in their list, but user is not logged into Joomla.  User is still a guest.

Thank you

**Comment by glena** [comment]
can you check the `New User Registration Group` setting under `global configuration` > `user management` in the joomla administrator?

This is what defines which role has the new users after signup.
 
![image](https://cloud.githubusercontent.com/assets/5647310/12419765/e18c3f3e-be96-11e5-8def-96c120e41b83.png)

**Comment by Beejer** [comment]
The New User Registration Group is set to "Registered".


------ Original Message ------

**Comment by glena** [comment]
I just tried and works fine.

The only issue I had with `registered` role, is that the menu keeps showing the login button but this is related to the joomla ACL and how do you configure the permissions.

Just to test, can you set the default role to `author` like in the screenshot I shared before?

**Comment by Beejer** [comment]
Set to "Author", but user still does not show in Joomla after logging 
in.


------ Original Message ------

**Comment by glena** [comment]
wait `but user still does not show in Joomla after logging`. Are you able to see the user in the joomla users list?

**Comment by Beejer** [comment]
Yes, the user is registered on the site.  Set the user group to 
"Author", but not difference.


------ Original Message ------

**Comment by glena** [comment]
I assume you tested with a new signup right?
The new user was created with role `author`?

**Comment by Beejer** [comment]
No, it's an existing user.  Do all user registrations need to come from 
the Auth0 form?


------ Original Message ------

**Comment by glena** [comment]
I dont understand your question.

In previous comments you said that the user exists in the auth0 database `User is authenticated in Auth0 and shows up in their list`.

The flow is the following, a user signup in auth0 (or maybe it already exists there because he signed up for another app that uses auth0 too) and then log in into joomla using the auth0 widget. The module will check if the user exists and if it does it will log the user in, if not it will create a new user with the default role.

**Comment by Beejer** [comment]
The user shows in Auth0 as having logged in 5 times today, in Joomla as 
logging in "Never".


------ Original Message ------

**Comment by glena** [comment]
Did you set the callback url in your auth0 app configuration?

it should be `http://YOURHOMEPAGE/index.php/component/auth0/?task=auth`.

so if your home page is `www.blog.com` the callback should be:

`http://www.blog.com/index.php/component/auth0/?task=auth`

**Comment by Beejer** [comment]
Yes, the callback URL is set.

I took a closer look, and there's a few issues with the controller 
script:

1. It's dependent on "nickname" being set to the username on Auth0.

2. It only creates an entry in the auth0_joomla_connect table if the 
user does not already exist in Joomla.

3. The Auth0 user_id doesn't work for me in raw format: ['user_id'] => 
auth0|357


------ Original Message ------

**Comment by glena** [comment]
1. Yes, you can enable usernames for your users in the database connection settings
2. you are right, this should be easy to fix
3. why?

About the point 2, I can change it but first I need you to confirm if new signups works (try with another email, one that it not being used in your joomla) as I asked before? I need to confirm that it works for new users.
